{{- if .Values.notifications.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-cd.notifications.fullname" . }}
  {{- if .Values.global.argocdNamespace }}
  namespace: {{ .Values.global.argocdNamespace }}
  {{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.notifications.name "name" .Values.notifications.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argo-cd.notifications.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "argo-cd.notificationsServiceAccountName" . }}
    namespace: {{ default .Release.Namespace .Values.global.argocdNamespace }}
{{- end }}
