apiVersion: v1
name: devops
version: 0.3.0
displayName:
  zh: DevOps
  en: DevOps
description:
  zh: DevOps 项目是一个独立的命名空间，其中定义了一组流水线。用户可以按照自己的方式对流水线进行分组（例如：项目类型、组织类型）。
  en: A DevOps project is a separate namespace where a set of pipelines is defined. Users can group their pipelines themselves (for example, project type and organization type).
category: integration-delivery
keywords:
  - DevOps
  - CICD
  - Others
home: https://www.kubesphere.io/devops/
sources:
  - https://github.com/kubesphere-extensions/devops
kubeVersion: ">=1.19.0"
ksVersion: ">=4.0.0-beta"
provider:
  en:
    name: "QingCloud Technologies"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.io"
  zh:
    name: "北京青云科技股份有限公司"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.com.cn"
maintainers:
  - name: jackyu
    email: jackyu@yunify.com
  - name: yazhouhu
    email: yazhouhu@yunify.com
staticFileDirectory: static
icon: ./static/devops-icon.png
screenshots:
  - ./static/screenshots/devops-screenshot-1.png
  - ./static/screenshots/devops-screenshot-2.png
  - ./static/screenshots/devops-screenshot-3.png
installationMode: Multicluster
dependencies:
  - name: extension
    tags:
      - extension
  - name: agent
    tags:
      - agent
