kind: ClusterRole
rules:
  - verbs:
      - 'create'
      - 'patch'
      - 'update'
      - 'get'
    apiGroups:
      - 'extensions.kubesphere.io'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resourcses:
      - 'namespaces'
      - 'configmaps'
      - 'limitranges'
      - 'resourcequotas'
  - verbs:
      - '*'
    apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
  - verbs:
      - '*'
    apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - '*'

---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - 'networking.k8s.io'
    resources:
      - 'ingresses'
      - 'networkpolicies'
  - verbs:
      - '*'
    apiGroups:
      - 'devops.kubesphere.io'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - 'monitoring.coreos.com'
    resources:
      - '*'
