web:
  enabled: true
  image:
    repository: docker.io/donniean/devops-frontend
    tag: latest

devops:
  enabled: true
  image:
    registry: kubespheredev/kubesphere
    controller:
      repository: devops-controller
      tag: latest
    apiserver:
      repository: devops-apiserver
      tag: latest
    tools:
      repository: devops-tools
      tag: latest
  jenkins:
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi
