
devops:
  enabled: true
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    controller:
      repository: devops-controller
      tag: dev-9cb5a2a
    apiserver:
      repository: devops-apiserver
      tag: dev-9cb5a2a
    tools:
      repository: devops-tools
      tag: dev-9cb5a2a
  jenkins:
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi

frontend:
  enabled: true
  image:
    repository: docker.io/donniean/devops-frontend
    tag: latest