extension:
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    frontend:
      repository: devops-frontend
      tag: dev-0804
    apiserver:
      repository: devops-apiserver
      tag: dev-9ea8e5a

agent:
  global:
    # the ks-core api
    # if want to access to jenkinsUI, the ksCoreApi must be specified and browser-accessible
    ksCoreApi: "http://ks-apiserver.kubesphere-system.svc:30881"
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    controller:
      repository: devops-controller
      tag: dev-9ea8e5a
    apiserver:
      repository: devops-apiserver
      tag: dev-9ea8e5a
    tools:
      repository: devops-tools
      tag: dev-9ea8e5a
  jenkins:
    Master:
      Image: registry.cn-huhehaote.aliyuncs.com/ksluban/jenkins
      ImageTag: v4.0.0-2.346.3
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi
