
devops:
  enabled: true
  global:
    # the api url of ks-core, the host must be browser-accessible
    ksCoreApi: "http://ks-apiserver.kubesphere-system.svc:30881"
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    controller:
      repository: devops-controller
      tag: dev-e502dec
    apiserver:
      repository: devops-apiserver
      tag: dev-e502dec
    tools:
      repository: devops-tools
      tag: dev-745ba06
  jenkins:
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi

frontend:
  enabled: true
  image:
    repository: docker.io/donniean/devops-frontend
    tag: latest