frontend:
  enabled: true
  image:
    repository: docker.io/donniean/devops-frontend
    tag: latest

backend:
  enabled: true
  image:
    registry: kubespheredev/kubesphere
    controller:
      repository: devops-controller
      tag: latest
    apiserver:
      repository: devops-apiserver
      tag: latest
    tools:
      repository: devops-tools
      tag: latest
