web:
  enabled: true
  image:
    repository: docker.io/spike2044/devops-ext
    tag: 230531

devops:
  enabled: true
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/jackyu-testing
    controller:
      repository: devops-controller
      tag: dev-1cebc8b
    apiserver:
      repository: devops-apiserver
      tag: dev-1cebc8b
    tools:
      repository: devops-tools
      tag: dev-1cebc8b
  jenkins:
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi
