extension:
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    frontend:
      repository: devops-frontend
      tag: dev-0810
    apiserver:
      repository: devops-apiserver
      tag: dev-1d12729

agent:
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    controller:
      repository: devops-controller
      tag: dev-1d12729
    apiserver:
      repository: devops-apiserver
      tag: dev-1d12729
    tools:
      repository: devops-tools
      tag: dev-9ea8e5a
  jenkins:
    securityRealm:
      openIdConnect:
        # the kubesphere-core api used for jenkins OIDC
        # if want to access to jenkinsUI, the ksCoreApi must be specified and browser-accessible
        kubesphereCoreApi: "http://ks-apiserver.kubesphere-system.svc:30881"
    Master:
      Image: registry.cn-huhehaote.aliyuncs.com/ksluban/jenkins
      ImageTag: v4.0.0-2.346.3
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi
