devops:
  enabled: true
  global:
    # the ks-core api
    # if want to access to jenkinsUI, the ksCoreApi must be specified and browser-accessible
    ksCoreApi: "http://ks-apiserver.kubesphere-system.svc:30881"
  image:
    registry: registry.cn-huhehaote.aliyuncs.com/ksluban
    controller:
      repository: devops-controller
      tag: dev-e502dec
    apiserver:
      repository: devops-apiserver
      tag: dev-e502dec
    tools:
      repository: devops-tools
      tag: dev-745ba06
  jenkins:
    Master:
      Image: registry.cn-huhehaote.aliyuncs.com/ksluban/jenkins
      ImageTag: v4.0.0-2.346.3
      resources:
        requests:
          cpu: 0.5
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi # recommend keep same as requests.memory
    Persistence:
      size: 8Gi

frontend:
  enabled: true
  image:
    repository: docker.io/donniean/devops-frontend
    tag: latest