apiVersion: v1
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 10
      authenticateRateLimiterDuration: 10m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      jwtSecret: {{ .Values.authentication.jwtSecret | quote }}

    ldap:
      host: openldap.kubesphere-system.svc:389
      managerDN: cn=admin,dc=kubesphere,dc=io
      managerPassword: admin
      userSearchBase: ou=Users,dc=kubesphere,dc=io
      groupSearchBase: ou=Groups,dc=kubesphere,dc=io

    devops:
      host: http://{{ .Release.Name }}-jenkins.{{ default .Release.Namespace .Values.global.namespace }}
      username: admin
      password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY4NjY3MjE3MywiaXNzIjoia3ViZXNwaGVyZSIsIm5iZiI6MTY4NjY3MjE3M30.NYVz6Bkd9A7v5umaZ1292H-xpFAxXHrlEM-A4hyKciY
      maxConnections: 100
      namespace: {{ default .Release.Namespace .Values.global.namespace }}
    {{ if .Values.jenkins.enabled }}
      workerNamespace: {{ .Values.jenkins.Agent.WorkerNamespace }}
    {{ end }}
kind: ConfigMap
metadata:
  name: devops-config
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
