{{- if .Values.global.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubesphere.io/namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namespace }}
{{- end }}