apiVersion: v1
kind: List
items:
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: workspace-view-devops
      annotations:
        iam.kubesphere.io/role-template-rules: '{"devops": "view"}'
      labels:
        iam.kubesphere.io/category: devops-projects
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/workspace: ""
    spec:
      displayName:
        en: DevOps Project Viewing
        zh: DevOps 项目查看
      description:
        en: View all DevOps projects in the workspace
        zh: 查看企业空间中的所有 DevOps 项目
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelines
            - pipelines/runs
            - pipelines/pipelineruns
            - pipelines/branches
            - pipelines/checkScriptCompile
            - pipelines/consolelog
            - pipelines/scan
            - pipelines/sonarstatus
            - pipelineruns
            - pipelineruns/nodedetails
            - checkCron
            - credentials
            - credentials/usage
            - roles
            - members
            - devops
            - devopsprojects
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: workspace-create-devops
      annotations:
        iam.kubesphere.io/dependencies: '["workspace-view-devops"]'
        iam.kubesphere.io/role-template-rules: '{"devops": "create"}'
      labels:
        iam.kubesphere.io/category: devops-projects
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/workspace: ""
    spec:
      displayName:
        en: DevOps Project Creation
        zh: DevOps 项目创建
      description:
        en: Create projects and become an administrator of that
        zh: 创建 DevOps 项目并成为其管理员
      rules:
        - apiGroups:
            - '*'
          resources:
            - devops
            - devopsprojects
          verbs:
            - create
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: workspace-manage-devops
      annotations:
        iam.kubesphere.io/dependencies: '["workspace-view-devops","workspace-view-members","workspace-create-devops"]'
        iam.kubesphere.io/role-template-rules: '{"devops": "manage"}'
      labels:
        iam.kubesphere.io/category: devops-projects
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/workspace: ""
    spec:
      displayName:
        en: DevOps Project Management
        zh: DevOps 项目管理
      description:
        en: Create, edit, and delete projects in the workspace
        zh: 创建、编辑和删除企业空间中的 DevOps 项目
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelines
            - pipelines/runs
            - pipelines/pipelineruns
            - pipelines/branches
            - pipelines/checkScriptCompile
            - pipelines/consolelog
            - pipelines/scan
            - pipelines/sonarstatus
            - pipelineruns
            - pipelineruns/nodedetails
            - checkCron
            - credentials
            - credentials/usage
            - roles
            - members
            - devops
            - devopsprojects
          verbs:
            - '*'

  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-view-credentials
      annotations:
        iam.kubesphere.io/role-template-rules: '{"credentials": "view"}'
      labels:
        iam.kubesphere.io/category: credentials
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Credential Viewing
        zh: 凭证查看
      description:
        en: View and use credentials in the DevOps project
        zh: 查看和使用 DevOps 项目中的凭证
      rules:
        - apiGroups:
            - '*'
          resources:
            - credentials
            - credentials/usage
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-manage-credentials
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-credentials"]'
        iam.kubesphere.io/role-template-rules: '{"credentials": "manage"}'
      labels:
        iam.kubesphere.io/category: credentials
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Credential Management
        zh: 凭证管理
      description:
        en: Create, edit and delete credentials in the DevOps project
        zh: 创建、编辑和删除 DevOps 项目中的凭证
      rules:
        - apiGroups:
            - '*'
          resources:
            - credentials
            - credentials/usage
          verbs:
            - '*'

  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-view-code-repository
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-credentials"]'
        iam.kubesphere.io/role-template-rules: '{"code-repository": "view"}'
      labels:
        iam.kubesphere.io/category: code-repositories
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Code Repository Viewing
        zh: 代码仓库查看
      description:
        en: View code repositories in the DevOps project
        zh: 查看 DevOps 项目中的代码仓库
      rules:
        - apiGroups:
            - devops.kubesphere.io
          resources:
            - gitrepositories
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-manage-code-repository
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-code-repository"]'
        iam.kubesphere.io/role-template-rules: '{"code-repository": "manage"}'
      labels:
        iam.kubesphere.io/category: code-repositories
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Code Repository Management
        zh: 代码仓库管理
      description:
        en: Manage code repositories in the DevOps project
        zh: 管理 DevOps 项目中的代码仓库
      rules:
        - apiGroups:
            - devops.kubesphere.io
          resources:
            - gitrepositories
          verbs:
            - '*'

  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-view-pipelineruns
      annotations:
        iam.kubesphere.io/role-template-rules: '{"pipelineruns": "view"}'
      labels:
        iam.kubesphere.io/category: pipelines
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: PipelineRuns Viewing
        zh: 流水线运行记录查看
      description:
        en: View pipelineruns in the DevOps project
        zh: 查看 DevOps 项目中的流水线运行记录
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelineruns
            - pipelines/runs
            - pipelines/pipelineruns
            - pipelineruns/artifacts
            - pipelineruns/nodedetails
            - pipelineruns/status
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-manage-pipelineruns
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-pipelines", "devops-view-pipelineruns"]'
        iam.kubesphere.io/role-template-rules: '{"pipelineruns": "manage"}'
      labels:
        iam.kubesphere.io/category: pipelines
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: PipelineRuns Management
        zh: 流水线运行管理
      description:
        en: 查看、删除 DevOps 项目中的流水线运行记录和下载制品
        zh: View、delete pipelineruns and download artifacts in the DevOps project
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelineruns
            - pipelines/runs
            - pipelines/pipelineruns
            - pipelineruns/nodedetails
            - pipelineruns/status
          verbs:
            - '*'
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-view-pipelines
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-pipelineruns", "devops-view-code-repository"]'
        iam.kubesphere.io/role-template-rules: '{"pipelines": "view", "pipelineruns":"view"}'
      labels:
        iam.kubesphere.io/category: pipelines
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Pipelines Viewing
        zh: 流水线查看
      description:
        en: View pipelines in the DevOps project
        zh: 查看 DevOps 项目中的流水线
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelines
            - pipelines/runs
            - pipelines/branches
            - pipelines/checkScriptCompile
            - pipelines/consolelog
            - pipelines/scan
            - pipelines/sonarstatus
            - jenkins/labelsData
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - list
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-manage-pipelines
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-pipelines", "devops-manage-pipelineruns",
        "devops-view-credentials"]'
        iam.kubesphere.io/role-template-rules: '{"pipelines": "manage", "pipelineruns":
        "manage"}'
      labels:
        iam.kubesphere.io/category: pipelines
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Pipelines Management
        zh: 流水线管理
      description:
        en: Create, edit and delete pipelines in the DevOps project
        zh: 创建、编辑和删除 DevOps 项目中的流水线
      rules:
        - apiGroups:
            - '*'
          resources:
            - pipelines
            - pipelines/runs
            - pipelines/branches
            - pipelines/checkScriptCompile
            - pipelines/consolelog
            - pipelines/scan
            - pipelines/sonarstatus
            - clustertemplates
            - clustertemplates/render
          verbs:
            - '*'

  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-view-gitops-applications
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-code-repository"]'
        iam.kubesphere.io/role-template-rules: '{"applications": "view"}'
      labels:
        iam.kubesphere.io/category: continuous-deployments
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Continuous Deployments Viewing
        zh: 持续部署查看
      description:
        en: View continuous deployments in the DevOps project
        zh: 查看 DevOps 项目中的持续部署
      rules:
        - apiGroups:
            - gitops.kubesphere.io
          resources:
            - applications
            - application-summary
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      name: devops-manage-gitops-applications
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-gitops-applications"]'
        iam.kubesphere.io/role-template-rules: '{"applications": "manage"}'
      labels:
        iam.kubesphere.io/aggregate-to-operator: ""
        iam.kubesphere.io/category: continuous-deployments
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
    spec:
      displayName:
        en: Continuous Deployments Management
        zh: 持续部署管理
      description:
        en: Create, edit and delete continuous deployments in the DevOps project
        zh: 创建、编辑和删除 DevOps 项目中的持续部署
      rules:
        - apiGroups:
            - gitops.kubesphere.io
          resources:
            - applications
          verbs:
            - '*'
        - apiGroups:
            - gitops.kubesphere.io
          resources:
            - clusters
          verbs:
            - list

  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-roles"]'
        iam.kubesphere.io/role-template-rules: '{"members": "view"}'
      labels:
        iam.kubesphere.io/category: access-control
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
      name: devops-view-members
    spec:
      displayName:
        en: Project Members Viewing
        zh: 项目成员查看
      description:
        en: View members in the DevOps project
        zh: 查看 DevOps 项目中的成员
      rules:
        - apiGroups:
            - '*'
          resources:
            - members
            - rolebindings
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      annotations:
        iam.kubesphere.io/dependencies: '["devops-view-members"]'
        iam.kubesphere.io/role-template-rules: '{"members": "manage"}'
      labels:
        iam.kubesphere.io/category: access-control
        iam.kubesphere.io/role-template: "false"
        scope.iam.kubesphere.io/devops: ""
      name: devops-manage-members
    spec:
      displayName:
        en: Project Members Management
        zh: 项目成员管理
      description:
        en: View members in the DevOps project
        zh: 管理 DevOps 项目中的成员
      rules:
        - apiGroups:
            - '*'
          resources:
            - members
            - rolebindings
          verbs:
            - '*'
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      annotations:
        iam.kubesphere.io/role-template-rules: '{"roles": "view"}'
      labels:
        iam.kubesphere.io/category: access-control
        iam.kubesphere.io/role-template: "true"
        scope.iam.kubesphere.io/devops: ""
      name: devops-view-roles
    spec:
      displayName:
        en: Project Roles View
        zh: 项目角色查看
      description:
        en: View roles in the DevOps project
        zh: 查看 DevOps 项目中的角色
      rules:
        - apiGroups:
            - '*'
          resources:
            - roles
          verbs:
            - get
            - list
            - watch
  - apiVersion: iam.kubesphere.io/v1beta1
    kind: RoleTemplate
    metadata:
      annotations:
        iam.kubesphere.io/role-template-rules: '{"roles": "manage"}'
      labels:
        iam.kubesphere.io/category: access-control
        iam.kubesphere.io/role-template: "false"
        scope.iam.kubesphere.io/devops: ""
      name: devops-manage-roles
    spec:
      displayName:
        en: Project Roles Management
      rules:
        - apiGroups:
            - '*'
          resources:
            - roles
          verbs:
            - '*'


