{{- if .Values.server.GKEfrontendConfig.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ template "argo-cd.server.fullname" . }}
  {{- if .Values.global.argocdNamespace }}
  namespace: {{ .Values.global.argocdNamespace }}
  {{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  {{- toYaml .Values.server.GKEfrontendConfig.spec | nindent 2 }}
{{- end }}
