{{- if .Values.Master.Jobs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-jobs
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
data:
{{ .Values.Master.Jobs | indent 2 }}
{{- end -}}
