{{- if .Values.configs.repositoryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repository-credentials
  {{- if .Values.global.argocdNamespace }}
  namespace: {{ .Values.global.argocdNamespace }}
  {{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" "secret") | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.configs.repositoryCredentials }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
